# Generated by Django 5.2.4 on 2025-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0002_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
